# Want to disable a check for a specific case? To disable checks inline:
# http://docs.rubocop.org/en/latest/configuration/#disabling-cops-within-source-code

# Begin with the 37signals house style
inherit_gem: { rubocop-37signals: rubocop.yml }

AllCops:
  TargetRubyVersion: 3.0
  Exclude:
    - "test/dummy/db/schema.rb"
